### PR TITLE
Minor updates to main web page

### PR DESCRIPTION
**Pull request by vicos59**
Just a one file pull request, for starters.

### CODE REVIEW

**Review by jonyo — APPROVED** [review]

**Comment by jonyo** [comment]
Looks good!  When I have time to, I'll merge and deploy the changes on the website.

Also congrats 🎉 !  Your first PR here!  Also, the first PR from someone besides me!  👍

**Comment by vicos59** [comment]
I've been busting butt migrating 1 of 2 last domains from my old server. Tons of PHP 5.4 code to update. As soon as I wrap that in a day or so I will be working on my classifieds migration full time, which means I'll be in full swing testing mode. If you have any significant changes merged and you want to build Beta 4, I'll be happy to update and use that as my baseline for moving forward.

**Comment by jonyo** [comment]
@vicos59 Did you mean to close the PR before it was merged?  Let me know if that was a mistake or on purpose for some reason. 

I just tested it and everything looks good, but don't want to just re-open to merge it without checking why you closed it?

**Comment by vicos59** [comment]
Ahhhh, duh. I thought you had merged it so I closed it. Not much sleep lately. LOL

**Comment by jonyo** [comment]
No worries!  Re-opening and merging now. FYI when a PR is merged it auto-closes.

**Comment by jonyo** [comment]
It is now deployed to the website!  Thanks again!

**Pull request merged**
